stages:
  - build
  - deploy

linux64:
  image: amityproject/linux64:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - make release-static
  except:
    - tags

  
LINUX64:
  image: amityproject/linux64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - make release-static
  - mv ./build/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags


win64:
  image: amityproject/win64:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-w64-mingw32
  except:
    - tags

  
WIN64:
  image: amityproject/win64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-w64-mingw32
  - mv ./build/x86_64-w64-mingw32/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import.exe
    - ./amity-blockchain-export.exe
    - ./amity-wallet-cli.exe
    - ./amity-wallet-rpc.exe
    - ./amityd.exe 
  only:
    - tags


macos64:
  image: amityproject/macos:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-apple-darwin11
  except:
    - tags


MACOS64:
  image: amityproject/macos:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-apple-darwin11
  - mv ./build/x86_64-apple-darwin11/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd   
  only:
    - tags


arm64:
  image: amityproject/aarch64:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=aarch64-linux-gnu
  except:
    - tags


ARM64:
  image: amityproject/aarch64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=aarch64-linux-gnu
  - mv ./build/aarch64-linux-gnu/release/bin/* ./  
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd  
  only:
    - tags

armhf:
  image: amityproject/armhf:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=arm-linux-gnueabihf
  except:
    - tags


ARMHF:
  image: amityproject/armhf:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=arm-linux-gnueabihf
  - mv ./build/arm-linux-gnueabihf/release/bin/* ./ 
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags


riscv64:
  image: amityproject/riscv64:builder
  stage: build
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=riscv64-linux-gnu
  except:
    - tags


RISCV64:
  image: amityproject/riscv64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=riscv64-linux-gnu
  - mv ./build/riscv64-linux-gnu/release/bin/* ./ 
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags
    